### PR TITLE
Ball resets if it rolls out of bounds

### PR DESCRIPTION
**Pull request by daniellarbourque**
[BOC-98:](https://bci4kids.atlassian.net/browse/BOC-98?atlOrigin=eyJpIjoiM2QwYmZmY2NmYmFkNDc4YmIxNmFhYjFmNzdmMjA2NjciLCJwIjoiaiJ9) Ball rolling out of bounds disappears

If the Boccia ball rolls out of bounds, it resets to its pre-drop position on the ramp.

An isTrigger collider component of the Boccia prefab sets the boundary. The size of the collider determines the size of the boundary. Note: The boundary size at the moment does not reflect the bounds of an actual Boccia court. Replicating the court will take place in [BOC-95](https://bci4kids.atlassian.net/browse/BOC-95?atlOrigin=eyJpIjoiZWZlMzJhMGZiOWMxNDUyN2EwZGY2OWMzMDNkZGNlN2IiLCJwIjoiaiJ9)

I also made sure that the jack ball would not instantiate outside the boundary, by adjusting the range values for the jack ball random position.

### CODE REVIEW

**Comment by gregbci** [comment]
Hi @daniellarbourque I was able to make the ball go out of bounds by rotating the ramp to ~90 degrees (shooting off to the left / right).  So, the bounds seem to work.  I noticed some issues along the way though:

1. The ball sometimes never resets... it just rolls to a near stop.  Maybe the velocity threshold is too small?
2. If the elevation is cranked up, the ball falls off the ramp when it resets.  This causes an infinite loop of balls falling off the ramp (until issue 1 happens).
3. When the ball resets, it just rolls down the ramp again.  This might be the same issue as 2, only the ball falls in front of the gate instead of off the ramp.  In this case, the ramp was rotated and the elevation was higher than the default.

I'm thinking it makes sense to address these while waiting for the fan to be ready.  Up to you.  If you want to just put these items in the backlog as known issues, we can do that too.

**Comment by daniellarbourque** [comment]
@gregbci I have been noticing these issues too the more I've been testing the ball movement for the different tasks. There is also another problem I noticed just a few minutes ago: if the ball collides with the jack, there is an issue with the reset similar to the 3rd issue you listed. 

I think it would be a good idea for me to work on these problems now, so I will get started on that. 

I also think some parts of the [Virtual Play support in model](https://bci4kids.atlassian.net/browse/BOC-70?atlOrigin=eyJpIjoiMDU2NTgxZTEyNTE4NDhkZDgyOGIyODM0MjJkOWE4N2EiLCJwIjoiaiJ9) task might be helpful, especially the "ball release" and "new ball."

**Comment by daniellarbourque** [comment]
@gregbci 

Here are the new changes I've made to fix the issues. Things should be working properly now, but let me know if you come across any problems.

Issue #1: The ball sometimes does not reset.
- The ball is supposed to reset after the `CheckBallSpeed` coroutine has detected that the ball has come to a near stop, but sometimes the ball never reset even though it had slowed down enough.
- The problem was that the coroutine starts immediately after the drop bar is opened. Sometimes, as the bar was still opening, the ball's velocity would have been below the threshold, which would call the `ResetBall()` method prematurely. 
- To fix this: I added an additional 1-second delay into the `DropBall()` coroutine, to make sure the ball gets rolling before we start to check its speed.

Issue #2, #3: Problems with the ball resetting to the correct location on the ramp
- The ball sometimes reset at the wrong location on the ramp (falling in front of the bar or off the back of the ramp). There were similar resetting problems after the ball went out of bounds or collided with the jack.
- The problem was that I was resetting the ball to its pre-drop position only - and not taking the ball's rotation into account.
- I added a variable called `dropRotation` to store the rotation of the ball right before it drops. In the reset method, I added `ball.transform.rotation = dropRotation;` and this seems to have solved those resetting issues.

Some other things I changed:
- I changed the hierarchy so that the boccia ball is no longer a child component of the ramp. Before, if the rotation/elevation buttons were pressed while the ball was still rolling across the floor, the ball would rotate/elevate as well, since it was a child component of the ramp. Now, the ball and ramp are separate objects to avoid this.
- In BallPresenter: The ResultBall() method is now NewBocciaBall(). A new ball is instantiated at the previous ball's pre-drop rotation and position when the previous ball comes to a near stop, instead of just moving the same ball back to where it was. One of my next tasks [BOC-94](https://bci4kids.atlassian.net/browse/BOC-94?atlOrigin=eyJpIjoiNTI3YTA0ZjgwOTgzNDk5OWJhZDg2MTczNjU2NDY4ZjUiLCJwIjoiaiJ9) will remove all of the balls already in the scene.

**Comment by gregbci** [comment]
Hey @daniellarbourque this is looking good.  I did a bit more exploratory testing and I was still able to get the ball to fall off the ramp:  Releasing the ball, let it roll off the ramp, then rotate the ramp.  It's seems like the reset position is cached at the time the ball is released?  Not sure.  Once the ball falls of the ramp, then we're stuck.

**Comment by daniellarbourque** [comment]
@gregbci I added a new commit so that the position and rotation for resetting the ball is now calculated relative to the ramp's elevation plate. This should ensure that the ball resets relative to the ramp's rotation and elevation, even if it changes while the ball is still rolling.

**Comment by gregbci** [comment]
Thanks, looks good!

**Pull request merged**
