### PR TITLE
Leave training when completed

### PR DESCRIPTION
**Pull request by daniellarbourque**
For the task: [BOC-67](https://bci4kids.atlassian.net/browse/BOC-67?atlOrigin=eyJpIjoiMmI2YTQ4N2RhNmRmNDU1ZDlkYTFkNDk1ZjExODBiNjIiLCJwIjoiaiJ9)

When training is completed, the training scene "disappears" by switching back to the Play Menu (as described in [UI Mockups | Training](https://bci4kids.atlassian.net/wiki/spaces/Boccia/pages/186384420/UI+Mockups#Training)). 

Changes made:

- In `TrainingPresenter`, when T is pressed to begin training, it also calls a new method in the model called `TrainingStarted()`
- Added a new `IsTraining` bool flag to the model, which is set to true by `model.TrainingStarted()`. `IsTraining` keeps track of whether or not training is in progress. 
- Created the `LSLMonitor.cs` script (located in Assets/Boccia/BCI) to read the `LSLMarkerStream` and update the model when it receives the ("Training Complete") marker, by calling the `model.TrainingComplete()` method. LSLMonitor only reads the stream if `IsTraining == true`. 
- Added the `TrainingComplete()` method to `BocciaModel` which sets `IsTraining` to false, and `BciTrained` to true. 
- When training is complete, `TrainingPresenter` updates the training instruction text, and then switches the screen back to the play menu. 
- Added to `HamburgerMenuPresenter` to deactivate the Hamburger Menu when `IsTraining == true`. This prevents the user from navigating away from the training screen while training is still in progress. 
- `LSLMonitor`, `TrainingPresenter`, and `HamburgerMenuPresenter` all subscribe to the `BciChanged` event. The `TrainingStarted()` and `TrainingComplete()` methods in `BocciaModel` both send out this event.

### CODE REVIEW

**Review by ekinney-lang — COMMENTED** [review]
There are a couple small tweaks that can make this work better. I'm also noting the few bugs that I have found.
1. When the training is happening, make it clearer that the hamburger menu is unavailable. It can be done in the Editor, to make the alpha option for "unavailable" much lower. Right now for someone like me with poor eyesight it still seemed "clickable".
2. Change "Training triggered." to "Training ongoing." or something else to indicate it is still happening.
3. The system does not have a reset option, in case someone wants to redo training. It seems that the only variable changed is the "BCITrained" boolean in BCIModel, but is worth noting that might happen.
4. Practical purposes - when using the single flash training, we have 90 seconds per trial if flashes are 9-12 for each trial. Reduce number of iterative flashes.
5. There is nothing that happens either on selection once trained. (Outside of scope I'm aware but logging it).
6. Selection response once trained is nonsense (Out of scope but logging).
7. There is a bug with our single flash algorithm - the last item in the array for flashing is always presented last.

**Comment by daniellarbourque** [comment]
1. I added a commit to address this
2. I added a commit to address this
3. I can add an option for resetting the training state in the model (to reset BciTrained). Is there a method from BCI Essentials that I would need to account for? Or can the user just press T again (after BciTrained has been reset) if they want to redo the training?
4. What would be some reasonable values to reduce the number of iterative flashes to? 

5-7: Thanks for pointing these out, Eli.

**Comment by ekinney-lang** [comment]
4. Let's drop it to 3-5 or somewhere in there for now. Thanks for adding the commits.

**Comment by ekinney-lang** [comment]
Looks good, I think that we can pull this in now, and tweak numbers later.

**Pull request merged**
